#!/bin/bash

#
#  https://github.com/0Magenta0/dotfiles
#  Copyright 0Magenta0 2022-2024
#  MIT License
#


# -=[ Imports ]=- #
source lib/common


# -=[ Functions ]=- #
# TODO: optional nvidia
# Prepares the /boot directory in the newly installed system.
#
# f_prepare_boot $mnt_path $disk $cpu_microcode
f_prepare_boot() {
  f_log 'Preparing /boot'
  arch-chroot "$1" bootctl install
  f_cp conf/boot "$1"
  f_exec echo "'\
title   Arch
linux   /vmlinuz-linux
initrd  /${3}.img
initrd  /initramfs-linux.img
options rd.luks.name=$(blkid -s UUID -o value "/dev/${2}2")=cryptroot root=/dev/mapper/cryptroot rw quiet nvidia_drm.modeset=1
'" '>' "${1}/boot/loader/entries/arch.conf"
}

# Prepares the /etc directory in the newly installed system.
#
# f_prepare_etc $mnt_path
f_prepare_etc() {
  f_log 'Preparing /etc'
  f_cp conf/etc "$1"
  f_exec genfstab -U "$1" '>>' "${1}/etc/fstab"
  f_exec_t chmod 440 "${1}/etc/sudoers"
}

# Configures some parts of the system.
#
# f_prepare_misc $mnt_path $user $password $groups
f_prepare_misc() {
  f_log 'Preparing misc'
  f_exec_t arch-chroot "$1" ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
  f_exec_t arch-chroot "$1" hwclock --systohc
  f_exec_t arch-chroot "$1" locale-gen

  f_exec_t arch-chroot "$1" mkinitcpio -P

  f_exec_t arch-chroot "$1" useradd -mG "$4" "$2"
  f_exec_t arch-chroot "$1" echo "${2}:${3}" '|' chpasswd
  f_exec_t arch-chroot "$1" echo "root:toor" '|' chpasswd

  f_exec_t arch-chroot "$1" systemctl enable --user pipewire
}

# Prepares the .config directory for certain user.
#
# f_prepare_dot_config $mnt_path $user
f_prepare_dot_config() {
  f_log "Preparing .config for ${2}"
  f_cp conf/.config "${1}/home/${2}/"
}
