#!/bin/bash

#
#  https://github.com/0Magenta0/dotfiles
#  Copyright 0Magenta0 2022-2024
#  MIT License
#


# -=[ Imports ]=- #
source lib/common


# -=[ Functions ]=- #
# Prepares passed disk and encrypts it.
# Layout:
#   1. EFI  (fat32)        : 1MiB 1025MiB
#   2. Root (LUKS -> ext4) : 1025MiB 100%
#
# f_prepare_disk $dev $crypt_root_name $mnt_path $crypt_key
f_prepare_disk() {
  f_exec parted --script "/dev/${1}" \
    mklabel gpt                      \
    mkpart EFI fat32 1MiB 1025MiB    \
    set 1 esp on                     \
    mkpart ROOT ext4 1025MiB 100%

  f_exec mkfs.vfat -F32 -n BOOT "/dev/${1}1"
  f_exec echo "$4" '|' cryptsetup -y -v luksFormat "/dev/${1}2"
  f_exec echo "$4" '|' cryptsetup open "/dev/${1}2" "$2"
  f_exec mkfs.ext4 "/dev/mapper/${2}"
  f_exec mount "/dev/mapper/${2}" "$3"
  f_exec mount --mkdir "/dev/${1}1" "${3}/boot"
}
