#!/bin/bash

#
#  https://github.com/0Magenta0/dotfiles
#  Copyright 0Magenta0 2022-2024
#  MIT License
#


# -=[ Imports ]=- #
source lib/common


# -=[ Functions ]=- #
# Prepares network in the newly installed system.
#
# f_network $mnt $dev $ip $gateway $hostname $dns 
f_network() {
  f_log 'Preparing network'

  f_exec_t echo "$5" '>' "${1}/etc/hostname"
  f_exec_t echo "nameserver ${6}" '>' "${1}/etc/resolv.conf"

  f_exec_t echo "'\
[Match]
Name=${2}

[Network]
Address=${3}/24
Gateway=${4}
DNS=${6}
'" '>' "${1}/etc/systemd/networkd/wired.network"

  f_exec_t echo "'\
[Resolve]
DNS=${6}
'" '>' "${1}/etc/systemd/resolved.conf"

  f_exec_t arch-chroot "$1" systemctl enable systemd-networkd
  f_exec_t arch-chroot "$1" systemctl enable systemd-resolved
}
